name: weibo-rank-bot

on:
  schedule:
    - cron: '30 1,17,20,22 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: hongyiheng/weibo-rank-bot@v0.0.5
        with:
          webhook: ${{ secrets.WEBHOOK }}
